name: Android CI

on:
  pull_request:
    paths:
      - .github/workflows/android-lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
 build:

   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v1
   - name: Set up JDK 17
     uses: actions/setup-java@v1
     with:
       java-version: 17
   - name: Make gradlew executable
     run: chmod +x ./gradlew
   - name: Build with Gradle    
     run: ./gradlew build
   
