name: Android CI

on:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*
      
jobs:

 build:
   name: Publish Image
   runs-on: ubuntu-latest
   
   steps:
   - name: Initialize Action
   - uses: actions/checkout@v2
   
   - name: Set up JDK 11
     uses: actions/setup-java@v2
     with:
       distribution: 'zulu'
       java-version: 11
       java-package: jdk
       
   - name: Make gradlew executable
     run: chmod +x ./gradlew
     
   - name: Check Lint Error
     run: ./gradlew lint --warning-mode all
     
   - name: Build with Gradle    
     run: ./gradlew build --warning-mode all
  
